title: The Way I See It
author: Ellen Flood
email: ellenflood1@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  I am using this space to explore data science techniques using open source data. Welcome :)

# social links
# twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
# github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage

theme: jekyll-theme-minimal

---

---
